name: lotuserp_comanda
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tab_indicator_styler: ^1.0.0
  shared_preferences: ^2.0.6
  http:
  flutter_svg: ^0.22.0
  progress_indicators: ^1.0.0
  page_transition: ^2.0.2
  flutter_snake_navigationbar: ^0.5.0
  cupertino_icons: ^1.0.2
  cherry_toast: ^1.0.0
  keyboard_visibility: ^0.5.6
  mobx:
  flutter_mobx:
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  mobx_codegen:
  build_runner:
  analyzer:
  intl:

flutter:
  assets:
    - "assets/icons/"
    - "assets/icons/bottom/"
    - "assets/icons/ordenation/"
    - "assets/images/"
    - "assets/images/categorys/"
    - "lib/assets/images/"
    - "lib/assets/icons/"

  fonts:
    - family: "Nunito Sans"
      fonts:
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-200i.ttf"
          style: "italic"
          weight: 200
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-300i.ttf"
          style: "italic"
          weight: 300
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-400i.ttf"
          style: "italic"
          weight: 400
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-600i.ttf"
          style: "italic"
          weight: 600
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-700i.ttf"
          style: "italic"
          weight: 700
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-800i.ttf"
          style: "italic"
          weight: 800
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-900i.ttf"
          style: "italic"
          weight: 900
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-200.ttf"
          weight: 200
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-300.ttf"
          weight: 300
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-400.ttf"
          weight: 400
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-600.ttf"
          weight: 600
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-700.ttf"
          weight: 700
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-800.ttf"
          weight: 800
        - asset: "assets/fonts/googleFonts/Nunito-Sans/Nunito-Sans-900.ttf"
          weight: 900

  uses-material-design: true

flutter_icons:
  image_path: "lib/assets/images/logo_transparente.png"
  android: "launcher_icon"
  ios: true
